// use client"; // 클라이언트 컴포넌트로 바꾸는 법.
import Link from "next/link";
import "./globals.css";




export const metadata = {
  // 웹페이지 제목과 설명
  title: "Web tutorials",
  description: "Generated by 심재윤",
};

export default async function RootLayout({ children }) {
  const resp = await fetch('http://localhost:9999/topics');
  const topics = await resp.json();  
  return (
    <html>
      <body>
        <h1><a href="/">WEB</a></h1>
        <ol>
          {/* <a>태그를 <Link> 컴포넌트로 바꿔주는 것만으로 속도가 빨라짐. */}
          {topics.map((topic) => {
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
